server {
    listen 8080;

    client_max_body_size 100M;
    client_body_buffer_size 10M;
    proxy_buffers 8 5M;
    proxy_buffer_size 5M;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /images {
        proxy_pass http://backend:8080/images;
    }
}