limit_req_zone $binary_remote_addr zone=auth_limit:10m rate=1r/s;

server {
    listen 8080;
    
    add_header X-Content-Type-Options nosniff;

    client_max_body_size 100M;
    client_body_buffer_size 10M;
    proxy_buffers 8 5M;
    proxy_buffer_size 5M;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /images {
        proxy_pass http://backend:8080/images;
    }

    location /auth/register {
        limit_req zone=auth_limit burst=5 nodelay;
        proxy_pass http://backend:8080/auth/register;
    }

    location /auth {
        proxy_pass http://backend:8080/auth;
    }

    location /admin/unsplash {
        proxy_pass http://backend:8080/admin/unsplash;
    }

    location /admin/users {
        proxy_pass http://backend:8080/admin/users;
    }
}