server {
    listen 80;

    # Allow up to 100M uploads
    client_max_body_size 100M;
    
    # Increase RAM buffers to prevent warnings for files under 10MB
    client_body_buffer_size 10M;
    proxy_buffers 8 5M;
    proxy_buffer_size 5M;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API requests to the backend container
    location /images {
        proxy_pass http://backend:8080/images;
    }
}